
#Container

gridshape: [90,90]
fitness_domain: [[0,55,],]
features_domain: [[0,30],[0,30]]

#Algorithm

algorithm: ME    #ME, NSLC or NS

budget: 1000000
batch_size: 1000

#Model

layers: [20, 10]
input_size: 63
output_size: 4

#Simulation

env_name: rocks_diamonds
feature1: "mean_nr_pos"
feature2: ""
episodes_per_eval: 3

#Output

save_period: 10