

#Container

gridshape: [90,90]
fitness_domain: [[0,55,],]
features_domain: [[0,30],[0,30],]

#Algorithm

algorithm: ME    #ME, NSLC or NS, NEAT

n_runs: 3
budget: 100000
batch_size: 1000
threshold_novelty: 0.2 # Not used for ME. For actions 5-10. For regular features, 0.5-1
capacity: 1000 #Used for NS, NSLC
ind_domain: [-30,30]
activation_function: relu # relu or tanh

#Model

layers: [20]
input_size: 63
output_size: 4

#Simulation

env_name: tomato_watering
feature1: "mean_nr_pos"
feature2: "mean_watered"
action_features: False

episodes_per_eval: 3

#Output

save_period: 0
